# Generated by Django 4.0 on 2022-01-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
